borderinfo = dict({'Austria':['Czech Republic','Germany','Hungary','Italy','Liechtenstein','Slovakia','Slovenia','Switzerland',],
                   'Croatia':['Bosnia and Herzegovina','Hungary','Montenegro','Serbia','Slovenia',],
                   'Estonia':['Latvia','Russia',],
                   'Latvia':['Belarus','Estonia','Lithuania','Russia',],
                   'Bulgaria':['Greece','Macedonia','Romania','Serbia','Turkey',],
                   'Luxembourg':['Belgium','France','Germany',],
                   'Slovakia':['Austria','Czech Republic','Hungary','Poland','Ukraine',],
                   'Ireland':['United Kingdom',],
                   'Portugal':['Spain',],
                   'Albania':['Greece','Kosovo','Macedonia','Montenegro',],
                   'Andorra':['France','Spain',],
                   'Belarus':['Latvia','Lithuania','Poland','Russia','Ukraine',],
                   'Belgium':['France','Germany','Luxembourg','Netherlands',],
                   'Bosnia and Herzegovina':['Croatia','Montenegro','Serbia',],
                   'Czech Republic':['Austria','Germany','Poland','Slovakia',],
                   'Denmark':['Germany',],
                   'Finland':['Norway','Russia','Sweden',],
                   'France':['Andorra','Belgium','Germany','Italy','Luxembourg','Monaco','Spain','Switzerland',],
                   'Germany':['Austria','Belgium','Czech Republic','Denmark','France','Luxembourg','Netherlands','Poland','Switzerland',],
                   'Gibraltar':['Spain',],
                   'Greece':['Albania','Bulgaria','Macedonia','Turkey',],
                   'Hungary':['Austria','Croatia','Romania','Serbia','Slovakia','Slovenia','Ukraine',],
                   'Italy':['Austria','France','San Marino','Slovenia','Switzerland','Vatican City',],
                   'Kosovo':['Albania','Macedonia','Montenegro','Serbia',],
                   'Liechtenstein':['Austria','Switzerland',],
                   'Lithuania':['Belarus','Latvia','Poland','Russia',],
                   'Macedonia':['Albania','Bulgaria','Greece','Kosovo','Serbia',],
                   'Moldova':['Romania','Ukraine',],
                   'Monaco':['France',],
                   'Montenegro':['Albania','Bosnia and Herzegovina','Croatia','Kosovo','Serbia',],
                   'Netherlands':['Belgium','Germany',],
                   'Norway':['Finland','Russia','Sweden',],
                   'Poland':['Belarus','Czech Republic','Germany','Lithuania','Russia','Slovakia','Ukraine',],
                   'Romania':['Bulgaria','Hungary','Moldova','Serbia','Ukraine',],
                   'San Marino':['Italy',],
                   'Serbia':['Bosnia and Herzegovina','Bulgaria','Croatia','Hungary','Kosovo','Macedonia','Montenegro','Romania',],
                   'Slovenia':['Austria','Croatia','Hungary','Italy',],
                   'Spain':['Andorra','France','Gibraltar','Morocco','Portugal',],
                   'Sweden':['Finland','Norway',],
                   'Switzerland':['Austria','France','Germany','Italy','Liechtenstein',],
                   'Ukraine':['Belarus','Hungary','Moldova','Poland','Romania','Russia','Slovakia',],
                   'United Kingdom':['Ireland',],
                   'Vatican City':['Italy',]})

def allCountries():
    return borderinfo.keys()

def borders(a, b):
    return borderinfo[a].contains(b)

